### PR TITLE
sendMessage is deprecated

### PR DESCRIPTION
**Pull request by davidjcralph**

### CODE REVIEW

**Comment by Falconerd** [comment]
I'm still getting updates in my test channel, but I'll make some time to look into this on the weekend. Thanks!

**Comment by ohlookitsderpy** [comment]
No problem!

**Comment by Falconerd** [comment]
I didn't really get a chance to look at it extensively this weekend. But, I think because the bot is still using like version 8 of Discord.js it won't break unless I update the version.

I will update the version and perhaps merge this PR when I get time to read through all the changes.

**Comment by Falconerd** [comment]
Well, we are still on version 9 and working for now.

**Pull request closed without merging**
