### PR TITLE
Added some debug output

### PR DESCRIPTION
**Pull request by Bluscream**
So you can see which repo of your config isn't working correctly. Also which repo has been updated.

### CODE REVIEW

**Comment by Falconerd** [comment]
Sorry, didn't see this as I've been busy moving to a new city. Will go over it when I can.

**Comment by Bluscream** [comment]
np man :)

**Comment by VelocityRa** [comment]
I'd like this to be merged as well, I've been thinking about adding that myself.

**Comment by Falconerd** [comment]
The reason I haven't merged this is because it's editing the built version of the file rather than the source. Sorry for not getting back to you sooner, I've been flat out with work.

**Pull request closed without merging**
